version: "3.7"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: edvdrm2004
      POSTGRES_DB: customers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: userregistration:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customers
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: edvdrm2004
    depends_on:
      - db
    ports:
      - "8081:8081"
volumes:
  postgres_data: